DROP TABLE IF EXISTS books;


CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  permissions INTEGER DEFAULT 0
);

CREATE TABLE books (
    id INTEGER PRIMARY KEY,
    author TEXT NOT NULL,
    title TEXT NOT NULL,
    isbn TEXT NOT NULL UNIQUE
);
